# Generated by Django 4.1.5 on 2023-05-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_alter_produit_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='image',
            new_name='img',
        ),
    ]
