# Generated by Django 4.2.1 on 2023-05-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_alter_produit_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='img',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
