# Generated by Django 4.2.1 on 2023-05-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0011_remove_produit_img_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/media'),
        ),
    ]
