# Generated by Django 4.1.7 on 2023-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_alter_categorie_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cat_name',
            field=models.CharField(choices=[('Alimentaire', 'Alimentaire'), ('Meuble', 'Meuble'), ('Sanitaire', 'Sanitaire'), ('Vaisselle', 'Vaisselle'), ('Vêtement', 'Vêtement'), ('Jouets', 'Jouets'), ('Linge de Maison', 'Linge de Maison'), ('Bijoux', 'Bijoux'), ('Décor', 'Décor')], default='Alimentaire', max_length=50),
        ),
    ]
